name: terraform-ci

on:
  push:
    paths:
      - terraform/**

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  security:
    uses: mmccarthy404/reusable-workflows/.github/workflows/scanning.yaml@main
    secrets: inherit

  terraform-ci:
    needs: security
    uses: mmccarthy404/reusable-workflows/.github/workflows/terraform-ci.yaml@main
    secrets: inherit
    with:
      terraform-version: 1.5.0
      terraform-directory: .
      terraform-var-file: terraform.tfvars
      terraform-backend-config: backend.tfvars
      aws-region: us-east-1
      aws-role: arn:aws:iam::004351562122:role/github-oidc-aws-core-infra